print("Hello, World!")
print("Habs herausgefunden!")

# Persönliche Informationen abfragen
namen = input("Gib deinen Namen ein: ")
print("Hallo, " + namen )
alter = input("Wie alt bist du? ")
print("Du bist also" + alter + " Jahre alt.")
gewicht = input("Wie viel wiegst du? ")
print("Du wiegst " + gewicht + " kg.")
größe = input("Wie groß bist du (in cm)? ")
print("Du bist " + größe + " cm groß.")
hobby = input("Was ist dein Hobby? ")
print("Dein Hobby ist " + hobby + ".")
lieblingsfarbe = input("Was ist deine Lieblingsfarbe? ")
print("Deine Lieblingsfarbe ist " + lieblingsfarbe + ".")
